source 'https://github.com/CocoaPods/Specs.git'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'startReactNative' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'Firebase/Analytics'
  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  
  target 'startReactNativeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'startReactNative-tvOS' do
  # Pods for startReactNative-tvOS

  target 'startReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
